---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: currency-exchange
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: web-api
     spec:
       containers:
         - name: forex-service
           image: us.gcr.io/currency-exchnage-214419/forex-service
           ports:
             - containerPort: 8000
             