---
 apiVersion: v1
 kind: Service
 metadata:
   name: currency-exchange
 spec:
   type: LoadBalancer
   ports:
   - port: 8888
     name: config-server-port
   - port: 8761
     name: eureka-naming-server-port
   - port: 8000
     name: forex-service-port
   - port: 8100
     name: currency-conversion-service-port
   - port: 8084
     name: currency-zuul-service-port
   selector:
     app: currency-exchange